# Generated by Django 2.0.2 on 2021-04-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deatil',
            new_name='detail',
        ),
    ]
